services:
  user-service:
    build: ./../../services/user-service
    container_name: user-service
    networks:
      - internal
    volumes:
      - ./../../services/user-service:/var/www
      - user-service-vendor:/var/www/vendor
      - user-service-bootstrap-cache:/var/www/bootstrap/cache
    env_file:
      - ./../../services/user-service/.env
    depends_on:
      - infra-postgres
      - infra-redis

  user-service-nginx:
    image: nginx:1.29.5-alpine
    container_name: user-service-nginx
    networks:
      - internal
      - edge
    ports:
      - "8001:80"
    volumes:
      - ./../../services/user-service:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service

volumes:
  user-service-vendor:
  user-service-bootstrap-cache:
